from UE4Parse.PakFile.PakObjects.ECompressionFlags import ECompressionFlags
from UE4Parse.PakFile.PakObjects.EPakVersion import EPakVersion
from UE4Parse.PakFile.PakObjects.FPakCompressedBlock import FPakCompressedBlock
